version: '3.7'

services:
  boilerplate_db:
    container_name: boilerplate_db
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PG_DATA=/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${TYPEORM_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # Change the left side to specify a different host port if needed
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root12345
    volumes:
      - ./data:/data # Map a local directory to store MinIO data
    command: server /data --console-address ":9090"
volumes:
  pgdata: