export const purchaseRequests = [
  {
    requestNumber: "PR-202501",
    requestTypeId: 1,
    departmentId: 1,
    branchId: 1,
    projectId: 1,
    requestDate: "2025-01-15",
    requiredDate: "2025-01-30",
    totalQty: 10,
    openQty: 5,
    receiptQty: 5,
    totalCost: 1000.0,
    totalEstimatedPrice: 1200.0,
    requestedBy: 1,
    priority: "High",
    currencyCode: "USD",
    status: "Pending",
    description: "Purchase request for office supplies",
    isApproved: false,
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        actualDate: "2025-01-16",
        lineItem: 1,
        itemCode: "ITM-001",
        itemName: "Laptop",
        unitId: 1,
        quantity: 5,
        estimationPrice: 1000.0,
        openQty: 2,
        receiptQty: 3,
        totalEstimatePrice: 5000.0,
        costCenter: 1,
        unitCode: "PC",
        note: "Urgent requirement",
        status: "Pending",
        createdBy: "admin_user",
      },
    ],
  },
  {
    requestNumber: "PR-202502",
    requestTypeId: 1,
    departmentId: 1,
    branchId: 1,
    projectId: 1,
    requestDate: "2025-02-10",
    requiredDate: "2025-02-25",
    totalQty: 20,
    openQty: 10,
    receiptQty: 10,
    totalCost: 2000.0,
    totalEstimatedPrice: 2200.0,
    requestedBy: 1,
    priority: "Medium",
    currencyCode: "USD",
    status: "Approved",
    description: "Purchase request for construction materials",
    isApproved: true,
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        actualDate: "2025-02-12",
        lineItem: 1,
        itemCode: "ITM-002",
        itemName: "Cement",
        unitId: 1,
        quantity: 10,
        estimationPrice: 100.0,
        openQty: 5,
        receiptQty: 5,
        totalEstimatePrice: 1000.0,
        costCenter: 1,
        unitCode: "BAG",
        note: "Bulk purchase for new site",
        status: "Approved",
        createdBy: "admin_user",
      },
    ],
  },
  {
    requestNumber: "PR-202503",
    requestTypeId: 1,
    departmentId: 1,
    branchId: 1,
    projectId: 1,
    requestDate: "2025-03-05",
    requiredDate: "2025-03-20",
    totalQty: 15,
    openQty: 5,
    receiptQty: 10,
    totalCost: 1500.0,
    totalEstimatedPrice: 1800.0,
    requestedBy: 1,
    priority: "Low",
    currencyCode: "USD",
    status: "Pending",
    description: "Purchase request for office chairs",
    isApproved: false,
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        actualDate: "2025-03-06",
        lineItem: 1,
        itemCode: "ITM-003",
        itemName: "Office Chair",
        unitId: 1,
        quantity: 10,
        estimationPrice: 150.0,
        openQty: 5,
        receiptQty: 5,
        totalEstimatePrice: 1500.0,
        costCenter: 1,
        unitCode: "PCS",
        note: "Ergonomic chairs",
        status: "Pending",
        createdBy: "admin_user",
      },
    ],
  },
  {
    requestNumber: "PR-202504",
    requestTypeId: 1,
    departmentId: 1,
    branchId: 1,
    projectId: 1,
    requestDate: "2025-04-10",
    requiredDate: "2025-04-25",
    totalQty: 25,
    openQty: 15,
    receiptQty: 10,
    totalCost: 2500.0,
    totalEstimatedPrice: 2700.0,
    requestedBy: 1,
    priority: "High",
    currencyCode: "USD",
    status: "Approved",
    description: "Purchase request for IT equipment",
    isApproved: true,
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        actualDate: "2025-04-12",
        lineItem: 1,
        itemCode: "ITM-004",
        itemName: "Monitor",
        unitId: 1,
        quantity: 5,
        estimationPrice: 250.0,
        openQty: 2,
        receiptQty: 3,
        totalEstimatePrice: 1250.0,
        costCenter: 1,
        unitCode: "PCS",
        note: "27-inch 4K monitor",
        status: "Approved",
        createdBy: "admin_user",
      },
    ],
  },
  {
    requestNumber: "PR-202505",
    requestTypeId: 1,
    departmentId: 1,
    branchId: 1,
    projectId: 1,
    requestDate: "2025-05-20",
    requiredDate: "2025-06-05",
    totalQty: 30,
    openQty: 10,
    receiptQty: 20,
    totalCost: 3000.0,
    totalEstimatedPrice: 3300.0,
    requestedBy: 1,
    priority: "Medium",
    currencyCode: "USD",
    status: "Pending",
    description: "Purchase request for electrical appliances",
    isApproved: false,
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        actualDate: "2025-05-22",
        lineItem: 1,
        itemCode: "ITM-005",
        itemName: "Air Conditioner",
        unitId: 1,
        quantity: 5,
        estimationPrice: 1200.0,
        openQty: 2,
        receiptQty: 3,
        totalEstimatePrice: 6000.0,
        costCenter: 1,
        unitCode: "PCS",
        note: "Energy-saving model",
        status: "Pending",
        createdBy: "admin_user",
      },
    ],
  },
];
