export const analysisCodes = [
  {
    id: 33,
    active: true,
    dimensionId: 6,
    code: "HL",
    nameEn: "Link House",
    nameKh: "លីងហៅស៍",
    dimension: {
      id: 6,
      active: true,
      code: "06",
      nameEn: "Unit Type",
      nameKh: "ប្រភេទផ្ទះ",
    },
  },
  {
    id: 32,
    active: true,
    dimensionId: 6,
    code: "HF",
    nameEn: "Flat House",
    nameKh: "ផ្ទះល្វែង",
    dimension: {
      id: 6,
      active: true,
      code: "06",
      nameEn: "Unit Type",
      nameKh: "ប្រភេទផ្ទះ",
    },
  },
  {
    id: 31,
    active: true,
    dimensionId: 2,
    code: "K",
    nameEn: "Block K",
    nameKh: "ប្លុក K",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 28,
    active: true,
    dimensionId: 2,
    code: "J",
    nameEn: "Block J",
    nameKh: "ប្លុក J",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 27,
    active: true,
    dimensionId: 2,
    code: "I",
    nameEn: "Block I",
    nameKh: "ប្លុក I",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 26,
    active: true,
    dimensionId: 2,
    code: "H",
    nameEn: "Block H",
    nameKh: "ប្លុក H",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 25,
    active: true,
    dimensionId: 2,
    code: "G",
    nameEn: "Block G",
    nameKh: "ប្លុក G",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 24,
    active: true,
    dimensionId: 2,
    code: "F",
    nameEn: "Block F",
    nameKh: "ប្លុក F",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 23,
    active: true,
    dimensionId: 2,
    code: "E",
    nameEn: "Block E",
    nameKh: "ប្លុក E",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 22,
    active: true,
    dimensionId: 2,
    code: "D",
    nameEn: "Block D",
    nameKh: "ប្លុក D",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 21,
    active: true,
    dimensionId: 2,
    code: "C",
    nameEn: "Block C",
    nameKh: "ប្លុក C",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 20,
    active: true,
    dimensionId: 2,
    code: "B",
    nameEn: "Block B",
    nameKh: "ប្លុក B",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 19,
    active: true,
    dimensionId: 2,
    code: "A",
    nameEn: "Block A",
    nameKh: "ប្លុក A",
    dimension: {
      id: 2,
      active: true,
      code: "02",
      nameEn: "Block",
      nameKh: "ប្លុក",
    },
  },
  {
    id: 18,
    active: true,
    dimensionId: 1,
    code: "PVM5",
    nameEn: "ML Vimean Mongkul IV (2)",
    nameKh: "អឹមអិល វិមានមង្គល ៤ (២)",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 17,
    active: true,
    dimensionId: 1,
    code: "PVM4",
    nameEn: "ML Vimean Mongkul IV (1)",
    nameKh: "អឹមអិល វិមានមង្គល ៤ (១)",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 16,
    active: true,
    dimensionId: 1,
    code: "PVM3",
    nameEn: "ML Vimean Mongkul III",
    nameKh: "អឹមអិល វិមានមង្គល ៣",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 15,
    active: true,
    dimensionId: 1,
    code: "PVM2",
    nameEn: "ML Vimean Mongkul II",
    nameKh: "អឹមអិល វិមានមង្គល ២",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 14,
    active: true,
    dimensionId: 1,
    code: "PVM1",
    nameEn: "ML Vimean Mongkul I",
    nameKh: "អឹមអិល វិមានមង្គល ១",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 13,
    active: true,
    dimensionId: 1,
    code: "PVL1",
    nameEn: "The ML Villa",
    nameKh: "ដឹអឹមអិល វីឡា",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 12,
    active: true,
    dimensionId: 1,
    code: "PTR1",
    nameEn: "ML Tiara",
    nameKh: "អឹមអិល ធារ៉ា",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 11,
    active: true,
    dimensionId: 1,
    code: "PSHV2",
    nameEn: "ML Sihanouk Ville II",
    nameKh: "អឹមអិល ក្រុងព្រះសីហនុ ២",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 10,
    active: true,
    dimensionId: 1,
    code: "PSHV1",
    nameEn: "ML Sihanouk Ville I",
    nameKh: "អឹមអិល ក្រុងព្រះសីហនុ ១",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 9,
    active: true,
    dimensionId: 1,
    code: "PPK2",
    nameEn: "The ML Park (Zone B)",
    nameKh: "ដឹអឹមអិល ផាក (តំបន់ B)",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 8,
    active: true,
    dimensionId: 1,
    code: "PPK1",
    nameEn: "The ML Park (Zone A)",
    nameKh: "ដឹអឹមអិល ផាក (តំបន់ A)",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
  {
    id: 7,
    active: true,
    dimensionId: 1,
    code: "PGL1",
    nameEn: "ML Green Land",
    nameKh: "អឹមអិល គ្រីនលែន",
    dimension: {
      id: 1,
      active: true,
      code: "01",
      nameEn: "Project",
      nameKh: "គម្រោង",
    },
  },
];
