export const departments = [
  {
    id: 7,
    active: true,
    code: "PRD",
    nameEn: "Procurement",
    nameKh: "ផ្គត់ផ្គង់",
    description: null,
  },
  {
    id: 6,
    active: true,
    code: "MKD",
    nameEn: "Marketing",
    nameKh: "ទីផ្សារ",
    description: null,
  },
  {
    id: 5,
    active: true,
    code: "ITD",
    nameEn: "Information Technology ",
    nameKh: "ព័ត៌មានវិទ្យា",
    description: "",
  },
  {
    id: 4,
    active: true,
    code: "HRD",
    nameEn: "Human Resource",
    nameKh: "ធនធានមនុស្ស",
    description: "",
  },
  {
    id: 3,
    active: true,
    code: "FND",
    nameEn: "Finance",
    nameKh: "ហិរញ្ញវត្ថុ",
    description: "",
  },
  {
    id: 2,
    active: true,
    code: "CTD",
    nameEn: "Construction",
    nameKh: "សំណង់",
    description: "",
  },
  {
    id: 1,
    active: true,
    code: "AMD",
    nameEn: "Administration",
    nameKh: "រដ្ឋបាល",
    description: "",
  },
];
