export const branches = [
  {
    id: 9,
    active: true,
    code: "MLTP",
    nameEn: "ML Dry Port",
    nameKh: "អឹមអិល ផែស្ងួត",
    contactPerson: null,
    phoneNumber: null,
    addressEn: "Takeo",
    addressKh: "តាកែវ",
    description: null,
  },
  {
    id: 8,
    active: true,
    code: "MLVM",
    nameEn: "ML VI MEAN MONGKUL",
    nameKh: "អឹមអិល វិមានមង្គល",
    contactPerson: null,
    phoneNumber: null,
    addressEn: null,
    addressKh: null,
    description: null,
  },
  {
    id: 7,
    active: true,
    code: "MLVL",
    nameEn: "THE ML VILLA",
    nameKh: "ដឹ អឹមអិល វីឡា",
    contactPerson: null,
    phoneNumber: null,
    addressEn: null,
    addressKh: null,
    description: null,
  },
  {
    id: 6,
    active: true,
    code: "MLTR",
    nameEn: "ML TIARA",
    nameKh: "អឹមអិល ធារ៉ា",
    contactPerson: null,
    phoneNumber: null,
    addressEn: null,
    addressKh: null,
    description: null,
  },
  {
    id: 5,
    active: true,
    code: "MLSHV",
    nameEn: "ML Sihanouk Ville",
    nameKh: "អឹមអិល ក្រុងព្រះសីហនុ",
    contactPerson: null,
    phoneNumber: null,
    addressEn: null,
    addressKh: null,
    description: null,
  },
  {
    id: 4,
    active: true,
    code: "MLPK",
    nameEn: "THE ML PARK",
    nameKh: "ដឹ អឹមអិល ផាក",
    contactPerson: null,
    phoneNumber: null,
    addressEn: null,
    addressKh: null,
    description: null,
  },
  {
    id: 3,
    active: true,
    code: "MLHO",
    nameEn: "ML Head Office",
    nameKh: "ស្នាក់ការកណ្ដាល អឹមអិល",
    contactPerson: null,
    phoneNumber: null,
    addressEn: "Phnom Penh",
    addressKh: "ភ្នំពេញ",
    description: null,
  },
  {
    id: 2,
    active: true,
    code: "MLGL",
    nameEn: "ML Green Land",
    nameKh: "អឹមអិល គ្រីនលែន",
    contactPerson: null,
    phoneNumber: null,
    addressEn: null,
    addressKh: null,
    description: null,
  },
];
