export const purchaseOrders = [
  {
    poNumber: "PO-202501",
    poTypeId: 1,
    branchId: 1,
    projectId: 1,
    vendorId: 1,
    vendorName: "ABC Supplies Ltd.",
    poDate: "2025-01-15",
    promisedDate: "2025-01-30",
    documentRef: "DOC-001",
    secondRef: "SR-001",
    poRef: "PO-REF-001",
    totalQty: 10,
    openQty: 5,
    receiptQty: 5,
    netAmount: 1000.0,
    totalDiscount: 50.0,
    totalAmount: 950.0,
    currencyCode: "USD",
    priority: "High",
    attachements: "invoice.pdf",
    description: "Purchase order for laptops",
    isApproved: false,
    status: "Pending",
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        lineItem: 1,
        itemCode: "ITM-001",
        itemName: "Laptop",
        unit: "PC",
        itemType: "Electronics",
        quantity: 5,
        unitPrice: 200.0,
        discount: 10.0,
        percentageDiscount: 5,
        netAmount: 950.0,
        amount: 1000.0,
        openQuantity: 2,
        receiptQuantity: 3,
        note: "Urgent requirement",
        costCenter: 1,
        requestDate: "2025-01-16",
        promisedDate: "2025-01-30",
        unitCode: "PC",
        status: "Pending",
        documentRef: "DOC-ITM-001",
        lineDocumentRef: "LINE-DOC-001",
        secondRef: "SR-ITM-001",
        createdBy: "admin_user",
        active: true,
      },
    ],
  },
  {
    poNumber: "PO-202502",
    poTypeId: 1,
    branchId: 1,
    projectId: 1,
    vendorId: 1,
    vendorName: "ABC Supplies Ltd.",
    poDate: "2025-02-10",
    promisedDate: "2025-02-25",
    documentRef: "DOC-002",
    secondRef: "SR-002",
    poRef: "PO-REF-002",
    totalQty: 20,
    openQty: 10,
    receiptQty: 10,
    netAmount: 2000.0,
    totalDiscount: 100.0,
    totalAmount: 1900.0,
    currencyCode: "USD",
    priority: "Medium",
    attachements: "invoice.pdf",
    description: "Purchase order for construction materials",
    isApproved: true,
    status: "Approved",
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        lineItem: 1,
        itemCode: "ITM-002",
        itemName: "Cement",
        unit: "BAG",
        itemType: "Construction",
        quantity: 10,
        unitPrice: 100.0,
        discount: 5.0,
        percentageDiscount: 5,
        netAmount: 950.0,
        amount: 1000.0,
        openQuantity: 5,
        receiptQuantity: 5,
        note: "Bulk purchase",
        costCenter: 1,
        requestDate: "2025-02-12",
        promisedDate: "2025-02-25",
        unitCode: "BAG",
        status: "Approved",
        documentRef: "DOC-ITM-002",
        lineDocumentRef: "LINE-DOC-002",
        secondRef: "SR-ITM-002",
        createdBy: "admin_user",
        active: true,
      },
    ],
  },
  {
    poNumber: "PO-202503",
    poTypeId: 1,
    branchId: 1,
    projectId: 1,
    vendorId: 1,
    vendorName: "ABC Supplies Ltd.",
    poDate: "2025-03-05",
    promisedDate: "2025-03-20",
    documentRef: "DOC-003",
    secondRef: "SR-003",
    poRef: "PO-REF-003",
    totalQty: 15,
    openQty: 5,
    receiptQty: 10,
    netAmount: 1500.0,
    totalDiscount: 75.0,
    totalAmount: 1425.0,
    currencyCode: "USD",
    priority: "Low",
    attachements: "invoice.pdf",
    description: "Purchase order for office chairs",
    isApproved: false,
    status: "Pending",
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        lineItem: 1,
        itemCode: "ITM-003",
        itemName: "Office Chair",
        unit: "PCS",
        itemType: "Furniture",
        quantity: 10,
        unitPrice: 150.0,
        discount: 10.0,
        percentageDiscount: 5,
        netAmount: 1425.0,
        amount: 1500.0,
        openQuantity: 5,
        receiptQuantity: 5,
        note: "Ergonomic chairs",
        costCenter: 1,
        requestDate: "2025-03-06",
        promisedDate: "2025-03-20",
        unitCode: "PCS",
        status: "Pending",
        documentRef: "DOC-ITM-003",
        lineDocumentRef: "LINE-DOC-003",
        secondRef: "SR-ITM-003",
        createdBy: "admin_user",
        active: true,
      },
    ],
  },
  {
    poNumber: "PO-202504",
    poTypeId: 1,
    branchId: 1,
    projectId: 1,
    vendorId: 1,
    vendorName: "ABC Supplies Ltd.",
    poDate: "2025-04-10",
    promisedDate: "2025-04-25",
    documentRef: "DOC-004",
    secondRef: "SR-004",
    poRef: "PO-REF-004",
    totalQty: 25,
    openQty: 15,
    receiptQty: 10,
    netAmount: 2500.0,
    totalDiscount: 125.0,
    totalAmount: 2375.0,
    currencyCode: "USD",
    priority: "High",
    attachements: "invoice.pdf",
    description: "Purchase order for IT equipment",
    isApproved: true,
    status: "Approved",
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        lineItem: 1,
        itemCode: "ITM-004",
        itemName: "Monitor",
        unit: "PCS",
        itemType: "Electronics",
        quantity: 5,
        unitPrice: 500.0,
        discount: 50.0,
        percentageDiscount: 10,
        netAmount: 2375.0,
        amount: 2500.0,
        openQuantity: 2,
        receiptQuantity: 3,
        note: "27-inch 4K monitor",
        costCenter: 1,
        requestDate: "2025-04-12",
        promisedDate: "2025-04-25",
        unitCode: "PCS",
        status: "Approved",
        documentRef: "DOC-ITM-004",
        lineDocumentRef: "LINE-DOC-004",
        secondRef: "SR-ITM-004",
        createdBy: "admin_user",
        active: true,
      },
    ],
  },
];
