export const purchaseQuotations = [
  {
    quotationNumber: "QTN-202501",
    quotationType: "Standard",
    branchId: 1,
    vendorId: 1,
    projectId: 1,
    requestDate: "2025-01-15",
    requestedById: 1,
    totalQty: 10,
    openQty: 5,
    receiptQty: 5,
    totalCost: 1000.0,
    isApproved: false,
    isRequireBidding: false,
    description: "Purchase quotation for laptops",
    currencyCode: "USD",
    documentReference: "DOC-001",
    status: "Pending",
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        warehouseId: 1,
        documentRef: "DOC-ITM-001",
        lineDocumentRef: "LINE-DOC-001",
        actualDate: "2025-01-16",
        lineItem: 1,
        itemCode: "ITM-001",
        itemName: "Laptop",
        unit: "PC",
        quantity: 5,
        estimatePrice: 1000.0,
        openQuantity: 2,
        receiptQuantity: 3,
        totalEstimatePrice: 5000.0,
        note: "Urgent requirement",
        isApproved: false,
        isRequireBidding: false,
        currencyCode: "USD",
        status: "Pending",
        createdBy: "admin_user",
      },
    ],
  },
  {
    quotationNumber: "QTN-202502",
    quotationType: "Urgent",
    branchId: 1,
    vendorId: 1,
    projectId: 1,
    requestDate: "2025-02-10",
    requestedById: 1,
    totalQty: 20,
    openQty: 10,
    receiptQty: 10,
    totalCost: 2000.0,
    isApproved: true,
    isRequireBidding: true,
    description: "Purchase quotation for construction materials",
    currencyCode: "USD",
    documentReference: "DOC-002",
    status: "Approved",
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        warehouseId: 1,
        documentRef: "DOC-ITM-002",
        lineDocumentRef: "LINE-DOC-002",
        actualDate: "2025-02-12",
        lineItem: 1,
        itemCode: "ITM-002",
        itemName: "Cement",
        unit: "BAG",
        quantity: 10,
        estimatePrice: 100.0,
        openQuantity: 5,
        receiptQuantity: 5,
        totalEstimatePrice: 1000.0,
        note: "Bulk purchase",
        isApproved: true,
        isRequireBidding: true,
        currencyCode: "USD",
        status: "Approved",
        createdBy: "admin_user",
      },
    ],
  },
  {
    quotationNumber: "QTN-202503",
    quotationType: "Standard",
    branchId: 1,
    vendorId: 1,
    projectId: 1,
    requestDate: "2025-03-05",
    requestedById: 1,
    totalQty: 15,
    openQty: 5,
    receiptQty: 10,
    totalCost: 1500.0,
    isApproved: false,
    isRequireBidding: false,
    description: "Purchase quotation for office chairs",
    currencyCode: "USD",
    documentReference: "DOC-003",
    status: "Pending",
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        warehouseId: 1,
        documentRef: "DOC-ITM-003",
        lineDocumentRef: "LINE-DOC-003",
        actualDate: "2025-03-06",
        lineItem: 1,
        itemCode: "ITM-003",
        itemName: "Office Chair",
        unit: "PCS",
        quantity: 10,
        estimatePrice: 150.0,
        openQuantity: 5,
        receiptQuantity: 5,
        totalEstimatePrice: 1500.0,
        note: "Ergonomic chairs",
        isApproved: false,
        isRequireBidding: false,
        currencyCode: "USD",
        status: "Pending",
        createdBy: "admin_user",
      },
    ],
  },
  {
    quotationNumber: "QTN-202504",
    quotationType: "Urgent",
    branchId: 1,
    vendorId: 1,
    projectId: 1,
    requestDate: "2025-04-10",
    requestedById: 1,
    totalQty: 25,
    openQty: 15,
    receiptQty: 10,
    totalCost: 2500.0,
    isApproved: true,
    isRequireBidding: true,
    description: "Purchase quotation for IT equipment",
    currencyCode: "USD",
    documentReference: "DOC-004",
    status: "Approved",
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        warehouseId: 1,
        documentRef: "DOC-ITM-004",
        lineDocumentRef: "LINE-DOC-004",
        actualDate: "2025-04-12",
        lineItem: 1,
        itemCode: "ITM-004",
        itemName: "Monitor",
        unit: "PCS",
        quantity: 5,
        estimatePrice: 500.0,
        openQuantity: 2,
        receiptQuantity: 3,
        totalEstimatePrice: 2500.0,
        note: "27-inch 4K monitor",
        isApproved: true,
        isRequireBidding: true,
        currencyCode: "USD",
        status: "Approved",
        createdBy: "admin_user",
      },
    ],
  },
  {
    quotationNumber: "QTN-202505",
    quotationType: "Standard",
    branchId: 1,
    vendorId: 1,
    projectId: 1,
    requestDate: "2025-05-20",
    requestedById: 1,
    totalQty: 30,
    openQty: 10,
    receiptQty: 20,
    totalCost: 3000.0,
    isApproved: false,
    isRequireBidding: false,
    description: "Purchase quotation for electrical appliances",
    currencyCode: "USD",
    documentReference: "DOC-005",
    status: "Pending",
    createdBy: "admin_user",
    items: [
      {
        branchId: 1,
        projectId: 1,
        warehouseId: 1,
        documentRef: "DOC-ITM-005",
        lineDocumentRef: "LINE-DOC-005",
        actualDate: "2025-05-22",
        lineItem: 1,
        itemCode: "ITM-005",
        itemName: "Air Conditioner",
        unit: "PCS",
        quantity: 5,
        estimatePrice: 1200.0,
        openQuantity: 2,
        receiptQuantity: 3,
        totalEstimatePrice: 6000.0,
        note: "Energy-saving model",
        isApproved: false,
        isRequireBidding: false,
        currencyCode: "USD",
        status: "Pending",
        createdBy: "admin_user",
      },
    ],
  },
];
