export const staffProfiles = [
  {
    staffCode: "STF-001",
    nameEn: "John Doe",
    nameKh: "ចន ដូ",
    sex: "Male",
    title: "Mr.",
    dateOfBirth: "1990-01-01",
    maritalStatus: "Single",
    nationality: "Cambodian",
    religion: "Buddhism",
    companyCardNo: "CCN-001",
    identityId: "ID-001",
    phone1: "+85512345678",
    phone2: "",
    workingEmail: "johndoe@company.com",
    personalEmail: "johndoe@gmail.com",
    placeOfBirth: "Phnom Penh",
    branchId: 1,
    departmentId: 1,
    positionId: 1,
    hiredDate: "2020-06-15",
    permanentAddress: "123 Street, Phnom Penh",
    currenAddress: "456 Street, Phnom Penh",
    profileImage: "profile_001.jpg",
    signatureImage: "signature_001.jpg",
    status: "Active",
    createdBy: "admin_user",
  },
  {
    staffCode: "STF-002",
    nameEn: "Jane Smith",
    nameKh: "ចេន ស្មីត",
    sex: "Female",
    title: "Ms.",
    dateOfBirth: "1992-02-15",
    maritalStatus: "Married",
    nationality: "Cambodian",
    religion: "Christianity",
    companyCardNo: "CCN-002",
    identityId: "ID-002",
    phone1: "+85598765432",
    phone2: "",
    workingEmail: "janesmith@company.com",
    personalEmail: "janesmith@gmail.com",
    placeOfBirth: "Siem Reap",
    branchId: 1,
    departmentId: 1,
    positionId: 1,
    hiredDate: "2021-05-10",
    permanentAddress: "789 Street, Siem Reap",
    currenAddress: "123 Street, Phnom Penh",
    profileImage: "profile_002.jpg",
    signatureImage: "signature_002.jpg",
    status: "Active",
    createdBy: "admin_user",
  },
  {
    staffCode: "STF-003",
    nameEn: "Sok Vichea",
    nameKh: "សុខ វិច្ឆា",
    sex: "Male",
    title: "Dr.",
    dateOfBirth: "1985-08-25",
    maritalStatus: "Single",
    nationality: "Cambodian",
    religion: "Buddhism",
    companyCardNo: "CCN-003",
    identityId: "ID-003",
    phone1: "+85511223344",
    phone2: "",
    workingEmail: "sokvichea@company.com",
    personalEmail: "sokvichea@gmail.com",
    placeOfBirth: "Battambang",
    branchId: 1,
    departmentId: 1,
    positionId: 1,
    hiredDate: "2019-09-20",
    permanentAddress: "456 Street, Battambang",
    currenAddress: "789 Street, Phnom Penh",
    profileImage: "profile_003.jpg",
    signatureImage: "signature_003.jpg",
    status: "Inactive",
    createdBy: "admin_user",
  },
  {
    staffCode: "STF-004",
    nameEn: "Chan Dara",
    nameKh: "ចាន់ ដារា",
    sex: "Male",
    title: "Mr.",
    dateOfBirth: "1988-07-12",
    maritalStatus: "Married",
    nationality: "Cambodian",
    religion: "Islam",
    companyCardNo: "CCN-004",
    identityId: "ID-004",
    phone1: "+85522334455",
    phone2: "",
    workingEmail: "chandara@company.com",
    personalEmail: "chandara@gmail.com",
    placeOfBirth: "Kampong Cham",
    branchId: 1,
    departmentId: 1,
    positionId: 1,
    hiredDate: "2018-03-10",
    permanentAddress: "123 Street, Kampong Cham",
    currenAddress: "456 Street, Phnom Penh",
    profileImage: "profile_004.jpg",
    signatureImage: "signature_004.jpg",
    status: "Active",
    createdBy: "admin_user",
  },
  {
    staffCode: "STF-005",
    nameEn: "Meas Srey",
    nameKh: "មាស ស្រី",
    sex: "Female",
    title: "Mrs.",
    dateOfBirth: "1993-11-30",
    maritalStatus: "Single",
    nationality: "Cambodian",
    religion: "Buddhism",
    companyCardNo: "CCN-005",
    identityId: "ID-005",
    phone1: "+85533445566",
    phone2: "",
    workingEmail: "meassrey@company.com",
    personalEmail: "meassrey@gmail.com",
    placeOfBirth: "Sihanoukville",
    branchId: 1,
    departmentId: 1,
    positionId: 1,
    hiredDate: "2022-01-05",
    permanentAddress: "555 Street, Sihanoukville",
    currenAddress: "123 Street, Phnom Penh",
    profileImage: "profile_005.jpg",
    signatureImage: "signature_005.jpg",
    status: "Pending",
    createdBy: "admin_user",
  },
];
