export const vendors = [
  {
    code: "V001",
    status: "ACTIVE",
    nameEn: "ABC Supplies Ltd.",
    nameKh: "ក្រុមហ៊ុន អេប៊ីស៊ី សផ្លាយ",
    vendorTypeId: 1,
    vendorClassId: 1,
    paymentTermId: 1,
    paymentMethodId: 1,
    title: "Mr.",
    contactPerson: "John Doe",
    phone1: "+85512345678",
    phone2: "+85598765432",
    workingEmail: "johndoe@abc.com",
    email: "info@abc.com",
    address: "No. 123, Phnom Penh, Cambodia",
    attachments: [1],
    vendorBanks: [
      {
        id: 1,
        bankId: "B001",
        accountNumber: "123456789",
        benifitsaryName: "ABC Supplies Ltd.",
        currency: "USD",
        countryCode: "KH",
        createdBy: "admin_user",
      },
    ],
    createdBy: "admin_user",
  },
  {
    code: "V002",
    status: "INACTIVE",
    nameEn: "XYZ Traders",
    nameKh: "ក្រុមហ៊ុន អេកអេសហ្ស៊ី ត្រេដឺស",
    vendorTypeId: 1,
    vendorClassId: 1,
    paymentTermId: 1,
    paymentMethodId: 1,
    title: "Ms.",
    contactPerson: "Jane Smith",
    phone1: "+85587654321",
    phone2: null,
    workingEmail: "janesmith@xyz.com",
    email: "support@xyz.com",
    address: "No. 456, Siem Reap, Cambodia",
    attachments: [1],
    vendorBanks: [
      {
        id: 1,
        bankId: "B001",
        accountNumber: "123456789",
        benifitsaryName: "XYZ Traders",
        currency: "USD",
        countryCode: "KH",
        createdBy: "admin_user",
      },
    ],
    createdBy: "admin_user",
  },
  {
    code: "V003",
    status: "ACTIVE",
    nameEn: "Mekong Wholesale",
    nameKh: "មេគង្គ ហូលសេល",
    vendorTypeId: 1,
    vendorClassId: 1,
    paymentTermId: 1,
    paymentMethodId: 1,
    title: "Dr.",
    contactPerson: "Sok Visal",
    phone1: "+85511223344",
    phone2: "+85555667788",
    workingEmail: "sokvisal@mekong.com",
    email: "admin@mekong.com",
    address: "No. 789, Battambang, Cambodia",
    attachments: [1],
    vendorBanks: [
      {
        id: 1,
        bankId: "B001",
        accountNumber: "123456789",
        benifitsaryName: "Mekong Wholesale",
        currency: "USD",
        countryCode: "KH",
        createdBy: "admin_user",
      },
    ],
    createdBy: "admin_user",
  },
  {
    code: "V004",
    status: "PENDING",
    nameEn: "Golden Rice Export",
    nameKh: "ក្រុមហ៊ុន អូស៊ីអេស",
    vendorTypeId: 1,
    vendorClassId: 1,
    paymentTermId: 1,
    paymentMethodId: 1,
    title: "Mr.",
    contactPerson: "Chan Dara",
    phone1: "+85522334455",
    phone2: null,
    workingEmail: "chandara@goldenrice.com",
    email: "info@goldenrice.com",
    address: "No. 999, Kampong Cham, Cambodia",
    attachments: [1],
    vendorBanks: [
      {
        id: 1,
        bankId: "B001",
        accountNumber: "123456789",
        benifitsaryName: "Golden Rice Export",
        currency: "USD",
        countryCode: "KH",
        createdBy: "admin_user",
      },
    ],
    createdBy: "admin_user",
  },
  {
    code: "V005",
    status: "ACTIVE",
    nameEn: "Lotus Construction",
    nameKh: "ក្រុមហ៊ុន ឡូតុស គនស្ត្រាក់សិន",
    vendorTypeId: 1,
    vendorClassId: 1,
    paymentTermId: 1,
    paymentMethodId: 1,
    title: "Mrs.",
    contactPerson: "Meas Srey",
    phone1: "+85533445566",
    phone2: "+85566778899",
    workingEmail: "meassrey@lotus.com",
    email: "contact@lotus.com",
    address: "No. 555, Sihanoukville, Cambodia",
    attachments: [1],
    vendorBanks: [
      {
        id: 1,
        bankId: "B001",
        accountNumber: "123456789",
        benifitsaryName: "Lotus Construction",
        currency: "USD",
        countryCode: "KH",
        createdBy: "admin_user",
      },
    ],
    createdBy: "admin_user",
  },
];
