export const warehouses = [
  {
    id: 15,
    code: "WHVM5",
    active: true,
    nameEn: "WH-ML Vimean Mongkul 4.2",
    nameKh: "ឃ្លាំង អឹមអិល វិមានមង្គល ៤.២.",
    description: null,
    createdAt: "2025-03-01T06:42:44.455Z",
    branch: {
      id: 2,
    },
  },
  {
    id: 14,
    code: "WHVM",
    active: true,
    nameEn: "WH-ML Vimean Mongkul 4.1",
    nameKh: "ឃ្លាំង អឹមអិល វិមានមង្គល ៤.១",
    description: null,
    createdAt: "2025-03-01T06:42:06.020Z",
    branch: {
      id: 2,
    },
  },
  {
    id: 13,
    code: "WHVL",
    active: true,
    nameEn: "WH-The ML Villa",
    nameKh: "ឃ្លាំង ដឹអឹមអិល វីឡា",
    description: null,
    createdAt: "2025-03-01T06:40:43.793Z",
    branch: {
      id: 3,
    },
  },
  {
    id: 12,
    code: "WHTR",
    active: true,
    nameEn: "WH-ML Tiara",
    nameKh: "ឃ្លាំង អឹមអិល ធារ៉ា",
    description: null,
    createdAt: "2025-03-01T06:39:58.498Z",
    branch: {
      id: 4,
    },
  },
  {
    id: 11,
    code: "WHTP1",
    active: true,
    nameEn: "WH-ML Dry Port (Takeo)",
    nameKh: "ឃ្លាំង អឹមអិល ផែស្ងួត (តាកែវ)",
    description: null,
    createdAt: "2025-03-01T06:39:32.550Z",
    branch: {
      id: 1,
    },
  },
  {
    id: 10,
    code: "WHSHV",
    active: true,
    nameEn: "WH-ML Sihanouk Ville",
    nameKh: "ឃ្លាំង អឹមអិល ក្រុងព្រះសីហនុ",
    description: null,
    createdAt: "2025-03-01T06:37:59.515Z",
    branch: {
      id: 5,
    },
  },
  {
    id: 9,
    code: "WHPK",
    active: true,
    nameEn: "WH-The ML Park",
    nameKh: "ឃ្លាំង ដឹអឹមអិល ផាក",
    description: null,
    createdAt: "2025-03-01T06:37:11.851Z",
    branch: {
      id: 6,
    },
  },
  {
    id: 8,
    code: "WHKV1",
    active: true,
    nameEn: "WH-ML King Villa",
    nameKh: "ឃ្លាំង អឹមអិល ឃីងវីឡា",
    description: null,
    createdAt: "2025-03-01T06:36:24.443Z",
    branch: {
      id: 7,
    },
  },
  {
    id: 7,
    code: "WHHO",
    active: true,
    nameEn: "WH-ML Head Office",
    nameKh: "ឃ្លាំង អឹមអិល ស្នាក់ការកណ្ដាល",
    description: null,
    createdAt: "2025-03-01T06:35:32.761Z",
    branch: {
      id: 7,
    },
  },
  {
    id: 6,
    code: "WHGL",
    active: true,
    nameEn: "WH-ML Green Land",
    nameKh: "ឃ្លាំង អឹមអិល គ្រីនលែន",
    description: null,
    createdAt: "2025-03-01T06:34:35.549Z",
    branch: {
      id: 8,
    },
  },
];
